name: Lint & PyTest on action
on: 
  pull_request:
    types:
      - opened
      - reopened
  push:  
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # Checkout codebase
      - name: Checkout code...
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      # Black formatter execution
      - name: Check files using the black formatter
        id: action_black
        uses: psf/black@stable
        with:
          options: "--pyi --safe --verbose"
          src: "./src"
          jupyter: true
          
      # Ruff linter execution
      - name: Check files using the Ruff linter
        uses: chartboost/ruff-action@v1
        with:
          args: "--fix --no-unsafe-fixes --no-cache"

      # Setup Conda env
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.11

      # Run PyTest 
      - name: Bash
        shell: bash -el {0}
        run: |
          conda info
          conda install pip
          pip install pytest pytest-cov pytest-html
          pip install datasets==2.15.0
          pip install .
          conda list
          pytest -s -v test\
             --junitxml=pytest.xml\
             --cov-report=term-missing:skip-covered\
             --cov=app | tee pytest-coverage.txt

      # Comment test result on commmit
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml

      # Commit & push changes
      - name: Check for modified files
        id: git-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT
      - name: Commit changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Add changes"
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.head_ref }}
          github_token: ${{ secrets.ACCESS_TOKEN }}
          force: true
          

      
