name: PyTest on action
on: 
  pull_request:
    types:
      - opened
      - reopened
  push:  
    branches:
      - main
jobs:
  run_pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code...
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: "3.10"

      - uses: dariocurr/pytest-summary@main
        with:
          extensions: pytest-asyncio pytest-cov
          options: -vv -s
          output: test-summary.md
          paths: test/**.py
