name: PyTest on action
on: 
  pull_request:
    types:
      - opened
      - reopened
  push:  
    branches:
      - main
jobs:
  run_pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code...
        uses: actions/checkout@v3

      - name: Check files using the black formatter
        id: action_black
        uses: psf/black@stable
        with:
          options: "--pyi --safe --verbose"
          src: "./src"
          jupyter: true
          
      - name: Check files using the Ruff linter
        uses: chartboost/ruff-action@v1
        with:
          args: "--fix --no-unsafe-fixes --no-cache"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install .
          pip list

      - name: Run PyTest
        uses: dariocurr/pytest-summary@main
        with:
          extensions: pytest-asyncio pytest-cov
          options: -vv -s
          output: test-summary.md
          show: "all"
          paths: test/**.py
